create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19,2) NOT NULL
);
insert into car (id, make, model, price) values (1, 'Chevrolet', 'Suburban 1500', '2.01');
insert into car (id, make, model, price) values (2, 'Dodge', 'Viper', '5.36');
insert into car (id, make, model, price) values (3, 'Acura', 'TL', '5.04');
insert into car (id, make, model, price) values (4, 'Volkswagen', 'GLI', '1.39');
insert into car (id, make, model, price) values (5, 'Volkswagen', 'GTI', '9.51');
insert into car (id, make, model, price) values (6, 'Dodge', 'Ram 1500 Club', '2.87');
insert into car (id, make, model, price) values (7, 'Nissan', '350Z', '4.65');
insert into car (id, make, model, price) values (8, 'Mitsubishi', 'Outlander', '8.58');
insert into car (id, make, model, price) values (9, 'Chevrolet', 'Monte Carlo', '7.63');
insert into car (id, make, model, price) values (10, 'Mitsubishi', 'Eclipse', '2.52');
insert into car (id, make, model, price) values (11, 'Audi', 'S4', '6.59');
insert into car (id, make, model, price) values (12, 'Ford', 'E350', '0.12');
insert into car (id, make, model, price) values (13, 'Ford', 'Fiesta', '9.74');
insert into car (id, make, model, price) values (14, 'Acura', 'TL', '9.56');
insert into car (id, make, model, price) values (15, 'GMC', 'Jimmy', '1.20');
insert into car (id, make, model, price) values (16, 'Ford', 'Mustang', '4.15');
insert into car (id, make, model, price) values (17, 'Ford', 'F350', '2.53');
insert into car (id, make, model, price) values (18, 'BMW', '525', '7.10');
insert into car (id, make, model, price) values (19, 'Acura', 'NSX', '8.91');
insert into car (id, make, model, price) values (20, 'Subaru', 'Outback', '8.65');
insert into car (id, make, model, price) values (21, 'Buick', 'Rendezvous', '6.10');
insert into car (id, make, model, price) values (22, 'Dodge', 'Neon', '0.53');
insert into car (id, make, model, price) values (23, 'Toyota', 'Prius', '0.06');
insert into car (id, make, model, price) values (24, 'Ford', 'Explorer Sport Trac', '2.31');
insert into car (id, make, model, price) values (25, 'BMW', 'X5', '2.29');
insert into car (id, make, model, price) values (26, 'BMW', '600', '3.14');
insert into car (id, make, model, price) values (27, 'Spyker', 'C8', '2.64');
insert into car (id, make, model, price) values (28, 'Acura', 'TL', '7.49');
insert into car (id, make, model, price) values (29, 'MG', 'MGB', '2.07');
insert into car (id, make, model, price) values (30, 'Volkswagen', 'Touareg', '0.59');
insert into car (id, make, model, price) values (31, 'Audi', 'Allroad', '6.23');
insert into car (id, make, model, price) values (32, 'Chevrolet', 'Cavalier', '9.30');
insert into car (id, make, model, price) values (33, 'Mercedes-Benz', 'E-Class', '3.48');
insert into car (id, make, model, price) values (34, 'Ford', 'EXP', '1.13');
insert into car (id, make, model, price) values (35, 'Maybach', '57', '7.26');
insert into car (id, make, model, price) values (36, 'Ford', 'Laser', '8.16');
insert into car (id, make, model, price) values (37, 'Cadillac', 'STS-V', '9.44');
insert into car (id, make, model, price) values (38, 'Lexus', 'LS', '6.53');
insert into car (id, make, model, price) values (39, 'Porsche', '911', '1.21');
insert into car (id, make, model, price) values (40, 'Mitsubishi', 'Eclipse', '5.92');
insert into car (id, make, model, price) values (41, 'BMW', 'Z3', '0.60');
insert into car (id, make, model, price) values (42, 'Land Rover', 'Discovery', '2.63');
insert into car (id, make, model, price) values (43, 'Volkswagen', 'Eurovan', '1.30');
insert into car (id, make, model, price) values (44, 'Nissan', 'Quest', '4.66');
insert into car (id, make, model, price) values (45, 'Land Rover', 'Discovery Series II', '0.46');
insert into car (id, make, model, price) values (46, 'Ford', 'Econoline E150', '7.22');
insert into car (id, make, model, price) values (47, 'Scion', 'xB', '9.53');
insert into car (id, make, model, price) values (48, 'Toyota', 'RAV4', '7.52');
insert into car (id, make, model, price) values (49, 'Toyota', 'Tacoma', '8.25');
insert into car (id, make, model, price) values (50, 'Chevrolet', 'Silverado', '7.02');
insert into car (id, make, model, price) values (51, 'Buick', 'Roadmaster', '3.97');
insert into car (id, make, model, price) values (52, 'Mitsubishi', 'Pajero', '9.47');
insert into car (id, make, model, price) values (53, 'Chevrolet', 'Corvette', '5.34');
insert into car (id, make, model, price) values (54, 'Plymouth', 'Neon', '7.38');
insert into car (id, make, model, price) values (55, 'Ford', 'GT500', '1.99');
insert into car (id, make, model, price) values (56, 'Toyota', 'Land Cruiser', '6.83');
insert into car (id, make, model, price) values (57, 'Buick', 'Riviera', '8.76');
insert into car (id, make, model, price) values (58, 'Ford', 'F350', '5.01');
insert into car (id, make, model, price) values (59, 'Honda', 'Civic', '5.27');
insert into car (id, make, model, price) values (60, 'Jaguar', 'XK Series', '5.12');
insert into car (id, make, model, price) values (61, 'Ford', 'Econoline E150', '6.15');
insert into car (id, make, model, price) values (62, 'Chrysler', 'Crossfire', '0.03');
insert into car (id, make, model, price) values (63, 'Acura', 'TSX', '5.57');
insert into car (id, make, model, price) values (64, 'Lexus', 'LS', '0.85');
insert into car (id, make, model, price) values (65, 'Maybach', '62', '1.64');
insert into car (id, make, model, price) values (66, 'Mazda', 'Mazdaspeed 3', '5.54');
insert into car (id, make, model, price) values (67, 'Dodge', 'Ram Wagon B350', '2.52');
insert into car (id, make, model, price) values (68, 'Mazda', '626', '5.87');
insert into car (id, make, model, price) values (69, 'Lexus', 'ES', '0.16');
insert into car (id, make, model, price) values (70, 'GMC', 'Envoy', '5.37');
insert into car (id, make, model, price) values (71, 'Subaru', 'Legacy', '9.68');
insert into car (id, make, model, price) values (72, 'Toyota', 'Tacoma', '1.55');
insert into car (id, make, model, price) values (73, 'Ford', 'Focus', '4.57');
insert into car (id, make, model, price) values (74, 'Ford', 'Ranger', '5.16');
insert into car (id, make, model, price) values (75, 'Buick', 'Regal', '5.37');
insert into car (id, make, model, price) values (76, 'Hummer', 'H3', '5.69');
insert into car (id, make, model, price) values (77, 'GMC', 'Savana 3500', '5.49');
insert into car (id, make, model, price) values (78, 'Chevrolet', 'Colorado', '8.49');
insert into car (id, make, model, price) values (79, 'Toyota', 'Tacoma', '7.41');
insert into car (id, make, model, price) values (80, 'Honda', 'Accord', '9.88');
insert into car (id, make, model, price) values (81, 'Dodge', 'Ram Van 1500', '6.23');
insert into car (id, make, model, price) values (82, 'Porsche', '924', '0.56');
insert into car (id, make, model, price) values (83, 'Mitsubishi', 'Outlander', '7.52');
insert into car (id, make, model, price) values (84, 'GMC', 'Envoy', '9.36');
insert into car (id, make, model, price) values (85, 'Dodge', 'Dakota', '3.82');
insert into car (id, make, model, price) values (86, 'Ford', 'F350', '1.08');
insert into car (id, make, model, price) values (87, 'Volkswagen', 'Golf III', '7.62');
insert into car (id, make, model, price) values (88, 'Buick', 'LeSabre', '5.42');
insert into car (id, make, model, price) values (89, 'Mitsubishi', 'Lancer Evolution', '1.29');
insert into car (id, make, model, price) values (90, 'Audi', 'Quattro', '8.06');
insert into car (id, make, model, price) values (91, 'BMW', '7 Series', '7.69');
insert into car (id, make, model, price) values (92, 'Ford', 'Econoline E250', '1.99');
insert into car (id, make, model, price) values (93, 'Dodge', 'Dakota Club', '2.68');
insert into car (id, make, model, price) values (94, 'BMW', '6 Series', '1.48');
insert into car (id, make, model, price) values (95, 'Saturn', 'L-Series', '8.37');
insert into car (id, make, model, price) values (96, 'Toyota', 'Land Cruiser', '3.34');
insert into car (id, make, model, price) values (97, 'Chevrolet', 'Prizm', '9.52');
insert into car (id, make, model, price) values (98, 'Kia', 'Sedona', '9.22');
insert into car (id, make, model, price) values (99, 'Mazda', 'Navajo', '2.57');
insert into car (id, make, model, price) values (100, 'Kia', 'Sephia', '9.87');
insert into car (id, make, model, price) values (101, 'Acura', 'Integra', '2.54');
insert into car (id, make, model, price) values (102, 'Ferrari', '458 Italia', '4.51');
insert into car (id, make, model, price) values (103, 'Maserati', 'GranTurismo', '4.19');
insert into car (id, make, model, price) values (104, 'Hummer', 'H1', '0.16');
insert into car (id, make, model, price) values (105, 'Ford', 'E-Series', '3.44');
insert into car (id, make, model, price) values (106, 'Pontiac', 'Firebird', '3.93');
insert into car (id, make, model, price) values (107, 'Toyota', 'Land Cruiser', '0.15');
insert into car (id, make, model, price) values (108, 'Mitsubishi', 'Cordia', '9.14');
insert into car (id, make, model, price) values (109, 'Subaru', 'Loyale', '5.60');
insert into car (id, make, model, price) values (110, 'GMC', 'Suburban 1500', '8.79');
insert into car (id, make, model, price) values (111, 'Dodge', 'Ram 3500', '7.77');
insert into car (id, make, model, price) values (112, 'Mercedes-Benz', 'CL-Class', '3.41');
insert into car (id, make, model, price) values (113, 'Mercury', 'Grand Marquis', '4.29');
insert into car (id, make, model, price) values (114, 'Land Rover', 'Discovery Series II', '3.67');
insert into car (id, make, model, price) values (115, 'Subaru', 'SVX', '2.72');
insert into car (id, make, model, price) values (116, 'Lexus', 'LS Hybrid', '2.07');
insert into car (id, make, model, price) values (117, 'Toyota', 'Prius', '4.97');
insert into car (id, make, model, price) values (118, 'Geo', 'Storm', '9.19');
insert into car (id, make, model, price) values (119, 'Ford', 'F150', '6.06');
insert into car (id, make, model, price) values (120, 'GMC', '1500 Club Coupe', '1.88');
insert into car (id, make, model, price) values (121, 'Dodge', 'D250 Club', '5.58');
insert into car (id, make, model, price) values (122, 'Maserati', 'Biturbo', '7.10');
insert into car (id, make, model, price) values (123, 'Cadillac', 'Fleetwood', '2.76');
insert into car (id, make, model, price) values (124, 'Isuzu', 'Amigo', '8.43');
insert into car (id, make, model, price) values (125, 'Audi', 'A4', '8.14');
insert into car (id, make, model, price) values (126, 'Mitsubishi', 'Outlander Sport', '5.14');
insert into car (id, make, model, price) values (127, 'Infiniti', 'I', '8.92');
insert into car (id, make, model, price) values (128, 'Chrysler', 'Crossfire', '6.33');
insert into car (id, make, model, price) values (129, 'Nissan', 'Frontier', '6.86');
insert into car (id, make, model, price) values (130, 'Ferrari', '430 Scuderia', '5.49');
insert into car (id, make, model, price) values (131, 'Mercury', 'Villager', '8.25');
insert into car (id, make, model, price) values (132, 'Toyota', 'Avalon', '3.98');
insert into car (id, make, model, price) values (133, 'BMW', '760', '7.03');
insert into car (id, make, model, price) values (134, 'Chevrolet', 'Corsica', '7.02');
insert into car (id, make, model, price) values (135, 'Volvo', 'XC90', '0.27');
insert into car (id, make, model, price) values (136, 'Ford', 'F350', '5.63');
insert into car (id, make, model, price) values (137, 'Mercedes-Benz', 'M-Class', '0.58');
insert into car (id, make, model, price) values (138, 'Mazda', 'B-Series Plus', '8.55');
insert into car (id, make, model, price) values (139, 'Plymouth', 'Neon', '1.94');
insert into car (id, make, model, price) values (140, 'Saab', '900', '0.17');
insert into car (id, make, model, price) values (141, 'Acura', 'MDX', '9.14');
insert into car (id, make, model, price) values (142, 'Chevrolet', 'Venture', '6.12');
insert into car (id, make, model, price) values (143, 'Dodge', 'Neon', '8.73');
insert into car (id, make, model, price) values (144, 'Porsche', 'Cayenne', '2.98');
insert into car (id, make, model, price) values (145, 'GMC', 'Rally Wagon 2500', '4.65');
insert into car (id, make, model, price) values (146, 'Cadillac', 'DeVille', '6.61');
insert into car (id, make, model, price) values (147, 'Chevrolet', 'Express 3500', '2.19');
insert into car (id, make, model, price) values (148, 'Chevrolet', '3500', '3.93');
insert into car (id, make, model, price) values (149, 'Land Rover', 'Defender', '5.21');
insert into car (id, make, model, price) values (150, 'BMW', '3 Series', '6.11');
insert into car (id, make, model, price) values (151, 'GMC', 'Savana 2500', '2.36');
insert into car (id, make, model, price) values (152, 'Mercedes-Benz', '300TE', '7.96');
insert into car (id, make, model, price) values (153, 'Nissan', '350Z', '6.62');
insert into car (id, make, model, price) values (154, 'Ford', 'Ranger', '7.16');
insert into car (id, make, model, price) values (155, 'Bentley', 'Continental Flying Spur', '8.40');
insert into car (id, make, model, price) values (156, 'Scion', 'xB', '6.19');
insert into car (id, make, model, price) values (157, 'Mitsubishi', 'Montero', '6.60');
insert into car (id, make, model, price) values (158, 'Ford', 'Explorer Sport Trac', '8.31');
insert into car (id, make, model, price) values (159, 'Hyundai', 'Scoupe', '4.15');
insert into car (id, make, model, price) values (160, 'Oldsmobile', 'Regency', '2.01');
insert into car (id, make, model, price) values (161, 'Toyota', 'TundraMax', '6.39');
insert into car (id, make, model, price) values (162, 'Chevrolet', 'Monte Carlo', '8.80');
insert into car (id, make, model, price) values (163, 'Volkswagen', 'Cabriolet', '0.29');
insert into car (id, make, model, price) values (164, 'BMW', 'M3', '7.02');
insert into car (id, make, model, price) values (165, 'Chrysler', 'New Yorker', '2.29');
insert into car (id, make, model, price) values (166, 'Infiniti', 'EX', '4.53');
insert into car (id, make, model, price) values (167, 'Mercedes-Benz', 'C-Class', '8.35');
insert into car (id, make, model, price) values (168, 'Ford', 'Th!nk', '1.57');
insert into car (id, make, model, price) values (169, 'Honda', 'Civic GX', '8.58');
insert into car (id, make, model, price) values (170, 'Ford', 'F350', '4.60');
insert into car (id, make, model, price) values (171, 'Suzuki', 'Forenza', '6.24');
insert into car (id, make, model, price) values (172, 'Mercury', 'Sable', '3.82');
insert into car (id, make, model, price) values (173, 'Jeep', 'Grand Cherokee', '7.90');
insert into car (id, make, model, price) values (174, 'Buick', 'LeSabre', '4.69');
insert into car (id, make, model, price) values (175, 'Mitsubishi', 'Truck', '0.62');
insert into car (id, make, model, price) values (176, 'Subaru', 'Impreza', '3.68');
insert into car (id, make, model, price) values (177, 'Mazda', 'Mazdaspeed 3', '8.09');
insert into car (id, make, model, price) values (178, 'Chevrolet', 'APV', '7.69');
insert into car (id, make, model, price) values (179, 'Chevrolet', 'Lumina', '8.98');
insert into car (id, make, model, price) values (180, 'Chevrolet', 'Impala', '7.29');
insert into car (id, make, model, price) values (181, 'Plymouth', 'Acclaim', '0.96');
insert into car (id, make, model, price) values (182, 'Mercury', 'Mystique', '6.74');
insert into car (id, make, model, price) values (183, 'Mercedes-Benz', 'SL-Class', '0.35');
insert into car (id, make, model, price) values (184, 'Ford', 'LTD Crown Victoria', '1.93');
insert into car (id, make, model, price) values (185, 'Buick', 'Century', '3.63');
insert into car (id, make, model, price) values (186, 'Subaru', 'Impreza', '0.09');
insert into car (id, make, model, price) values (187, 'Toyota', 'Land Cruiser', '4.96');
insert into car (id, make, model, price) values (188, 'Dodge', 'Grand Caravan', '8.82');
insert into car (id, make, model, price) values (189, 'Buick', 'Electra', '0.39');
insert into car (id, make, model, price) values (190, 'BMW', 'Z8', '7.48');
insert into car (id, make, model, price) values (191, 'Ford', 'E-Series', '3.48');
insert into car (id, make, model, price) values (192, 'Mercury', 'Sable', '9.62');
insert into car (id, make, model, price) values (193, 'Acura', 'MDX', '8.24');
insert into car (id, make, model, price) values (194, 'Kia', 'Rio', '3.90');
insert into car (id, make, model, price) values (195, 'Chevrolet', 'Camaro', '3.25');
insert into car (id, make, model, price) values (196, 'Oldsmobile', '98', '5.65');
insert into car (id, make, model, price) values (197, 'Chrysler', 'Sebring', '1.40');
insert into car (id, make, model, price) values (198, 'Hummer', 'H2', '0.59');
insert into car (id, make, model, price) values (199, 'Saturn', 'L-Series', '4.94');
insert into car (id, make, model, price) values (200, 'Toyota', 'FJ Cruiser', '2.50');
insert into car (id, make, model, price) values (201, 'Mazda', 'Familia', '3.67');
insert into car (id, make, model, price) values (202, 'Dodge', 'Grand Caravan', '9.68');
insert into car (id, make, model, price) values (203, 'Land Rover', 'Range Rover', '1.71');
insert into car (id, make, model, price) values (204, 'Pontiac', 'Sunfire', '2.92');
insert into car (id, make, model, price) values (205, 'Lexus', 'IS-F', '3.32');
insert into car (id, make, model, price) values (206, 'Hillman', 'Minx Magnificent', '2.70');
insert into car (id, make, model, price) values (207, 'Subaru', 'Impreza', '5.93');
insert into car (id, make, model, price) values (208, 'Toyota', 'MR2', '0.91');
insert into car (id, make, model, price) values (209, 'Pontiac', 'Grand Prix', '6.27');
insert into car (id, make, model, price) values (210, 'Nissan', 'Xterra', '7.84');
insert into car (id, make, model, price) values (211, 'Geo', 'Metro', '6.08');
insert into car (id, make, model, price) values (212, 'Toyota', 'Camry', '6.60');
insert into car (id, make, model, price) values (213, 'Volvo', 'S80', '3.35');
insert into car (id, make, model, price) values (214, 'Toyota', 'Land Cruiser', '0.97');
insert into car (id, make, model, price) values (215, 'Lexus', 'GS', '5.80');
insert into car (id, make, model, price) values (216, 'Chevrolet', 'Express 2500', '8.66');
insert into car (id, make, model, price) values (217, 'Ferrari', '458 Italia', '4.83');
insert into car (id, make, model, price) values (218, 'Nissan', 'Sentra', '6.96');
insert into car (id, make, model, price) values (219, 'Maserati', 'Biturbo', '1.32');
insert into car (id, make, model, price) values (220, 'Mitsubishi', 'Truck', '1.44');
insert into car (id, make, model, price) values (221, 'Mercedes-Benz', '400SE', '2.31');
insert into car (id, make, model, price) values (222, 'Dodge', 'Dakota', '4.64');
insert into car (id, make, model, price) values (223, 'Mazda', 'RX-7', '6.01');
insert into car (id, make, model, price) values (224, 'Mercedes-Benz', 'S-Class', '1.63');
insert into car (id, make, model, price) values (225, 'GMC', 'Envoy', '5.26');
insert into car (id, make, model, price) values (226, 'Pontiac', 'Grand Prix', '0.95');
insert into car (id, make, model, price) values (227, 'Chevrolet', 'Express 1500', '6.32');
insert into car (id, make, model, price) values (228, 'Porsche', '928', '9.56');
insert into car (id, make, model, price) values (229, 'Suzuki', 'Daewoo Magnus', '9.57');
insert into car (id, make, model, price) values (230, 'Toyota', 'Avalon', '1.90');
insert into car (id, make, model, price) values (231, 'Infiniti', 'G', '8.88');
insert into car (id, make, model, price) values (232, 'Chevrolet', 'Silverado', '5.78');
insert into car (id, make, model, price) values (233, 'Chrysler', 'Voyager', '9.78');
insert into car (id, make, model, price) values (234, 'Subaru', 'Forester', '1.71');
insert into car (id, make, model, price) values (235, 'Mazda', 'Mazda6', '3.39');
insert into car (id, make, model, price) values (236, 'Kia', 'Optima', '2.46');
insert into car (id, make, model, price) values (237, 'Mazda', 'RX-7', '1.87');
insert into car (id, make, model, price) values (238, 'Chevrolet', 'Express 1500', '6.86');
insert into car (id, make, model, price) values (239, 'Chevrolet', 'HHR', '5.36');
insert into car (id, make, model, price) values (240, 'Subaru', 'Impreza', '4.04');
insert into car (id, make, model, price) values (241, 'MINI', 'Countryman', '5.68');
insert into car (id, make, model, price) values (242, 'Volkswagen', 'GLI', '4.12');
insert into car (id, make, model, price) values (243, 'Scion', 'tC', '2.48');
insert into car (id, make, model, price) values (244, 'Ford', 'E350', '2.27');
insert into car (id, make, model, price) values (245, 'Saturn', 'VUE', '3.69');
insert into car (id, make, model, price) values (246, 'Mitsubishi', 'Lancer', '6.19');
insert into car (id, make, model, price) values (247, 'Audi', 'Allroad', '3.60');
insert into car (id, make, model, price) values (248, 'Chevrolet', 'Suburban 2500', '7.01');
insert into car (id, make, model, price) values (249, 'GMC', 'Envoy', '4.04');
insert into car (id, make, model, price) values (250, 'Mercury', 'Mariner', '5.13');
insert into car (id, make, model, price) values (251, 'BMW', 'M5', '8.11');
insert into car (id, make, model, price) values (252, 'Mercury', 'Cougar', '6.96');
insert into car (id, make, model, price) values (253, 'Audi', '80', '1.43');
insert into car (id, make, model, price) values (254, 'Cadillac', 'Seville', '8.62');
insert into car (id, make, model, price) values (255, 'MINI', 'Countryman', '6.47');
insert into car (id, make, model, price) values (256, 'Alfa Romeo', '164', '6.50');
insert into car (id, make, model, price) values (257, 'GMC', 'Envoy XUV', '0.76');
insert into car (id, make, model, price) values (258, 'Chevrolet', 'Impala', '2.31');
insert into car (id, make, model, price) values (259, 'Nissan', 'Altima', '8.63');
insert into car (id, make, model, price) values (260, 'Land Rover', 'Range Rover Evoque', '3.03');
insert into car (id, make, model, price) values (261, 'Nissan', 'Frontier', '8.41');
insert into car (id, make, model, price) values (262, 'Subaru', 'Forester', '1.52');
insert into car (id, make, model, price) values (263, 'GMC', 'Sierra 3500HD', '7.99');
insert into car (id, make, model, price) values (264, 'Mercury', 'Sable', '1.61');
insert into car (id, make, model, price) values (265, 'Porsche', 'Panamera', '1.88');
insert into car (id, make, model, price) values (266, 'Saturn', 'Sky', '6.80');
insert into car (id, make, model, price) values (267, 'Ford', 'Econoline E350', '3.61');
insert into car (id, make, model, price) values (268, 'BMW', 'Z4', '8.31');
insert into car (id, make, model, price) values (269, 'Nissan', 'JUKE', '0.01');
insert into car (id, make, model, price) values (270, 'Lincoln', 'Town Car', '8.03');
insert into car (id, make, model, price) values (271, 'Pontiac', 'GTO', '1.81');
insert into car (id, make, model, price) values (272, 'Chevrolet', 'Corvette', '8.55');
insert into car (id, make, model, price) values (273, 'Honda', 'CR-X', '4.98');
insert into car (id, make, model, price) values (274, 'Lincoln', 'Town Car', '9.21');
insert into car (id, make, model, price) values (275, 'BMW', 'M3', '7.21');
insert into car (id, make, model, price) values (276, 'Bentley', 'Continental GTC', '4.07');
insert into car (id, make, model, price) values (277, 'Hyundai', 'Tucson', '9.42');
insert into car (id, make, model, price) values (278, 'Dodge', 'Sprinter', '4.84');
insert into car (id, make, model, price) values (279, 'Jaguar', 'S-Type', '9.95');
insert into car (id, make, model, price) values (280, 'Lexus', 'LS', '7.28');
insert into car (id, make, model, price) values (281, 'Mitsubishi', 'Challenger', '7.93');
insert into car (id, make, model, price) values (282, 'Lincoln', 'Town Car', '1.65');
insert into car (id, make, model, price) values (283, 'Isuzu', 'Hombre', '7.80');
insert into car (id, make, model, price) values (284, 'Dodge', 'Dynasty', '3.57');
insert into car (id, make, model, price) values (285, 'Oldsmobile', 'Bravada', '2.54');
insert into car (id, make, model, price) values (286, 'Mercedes-Benz', 'GL-Class', '7.16');
insert into car (id, make, model, price) values (287, 'Mercedes-Benz', '500SL', '1.28');
insert into car (id, make, model, price) values (288, 'Audi', 'Q7', '7.94');
insert into car (id, make, model, price) values (289, 'Mazda', '323', '1.40');
insert into car (id, make, model, price) values (290, 'Ford', 'F-Series', '8.24');
insert into car (id, make, model, price) values (291, 'Ford', 'Freestar', '4.06');
insert into car (id, make, model, price) values (292, 'Acura', 'TSX', '9.97');
insert into car (id, make, model, price) values (293, 'Chevrolet', 'Camaro', '9.52');
insert into car (id, make, model, price) values (294, 'Nissan', 'Murano', '0.05');
insert into car (id, make, model, price) values (295, 'Volvo', '960', '4.51');
insert into car (id, make, model, price) values (296, 'BMW', '8 Series', '8.33');
insert into car (id, make, model, price) values (297, 'Infiniti', 'QX56', '0.32');
insert into car (id, make, model, price) values (298, 'Chevrolet', 'Malibu', '1.98');
insert into car (id, make, model, price) values (299, 'Chevrolet', 'Caprice', '3.41');
insert into car (id, make, model, price) values (300, 'Toyota', 'Venza', '2.00');
insert into car (id, make, model, price) values (301, 'Toyota', 'Matrix', '0.39');
insert into car (id, make, model, price) values (302, 'Ford', 'Escape', '7.25');
insert into car (id, make, model, price) values (303, 'Infiniti', 'QX', '7.82');
insert into car (id, make, model, price) values (304, 'GMC', 'Sonoma', '9.27');
insert into car (id, make, model, price) values (305, 'Mazda', 'MX-5', '9.37');
insert into car (id, make, model, price) values (306, 'Volvo', 'S70', '0.39');
insert into car (id, make, model, price) values (307, 'Chevrolet', 'Camaro', '4.07');
insert into car (id, make, model, price) values (308, 'Toyota', 'FJ Cruiser', '2.04');
insert into car (id, make, model, price) values (309, 'Mazda', 'CX-7', '0.52');
insert into car (id, make, model, price) values (310, 'Chevrolet', 'Malibu', '2.62');
insert into car (id, make, model, price) values (311, 'Jaguar', 'XF', '5.73');
insert into car (id, make, model, price) values (312, 'Subaru', 'Alcyone SVX', '8.85');
insert into car (id, make, model, price) values (313, 'Toyota', 'Venza', '5.17');
insert into car (id, make, model, price) values (314, 'Chevrolet', 'Tahoe', '3.57');
insert into car (id, make, model, price) values (315, 'Isuzu', 'Trooper', '3.63');
insert into car (id, make, model, price) values (316, 'Mercedes-Benz', 'W201', '0.24');
insert into car (id, make, model, price) values (317, 'Chrysler', 'Pacifica', '0.46');
insert into car (id, make, model, price) values (318, 'Chevrolet', 'Camaro', '2.08');
insert into car (id, make, model, price) values (319, 'Chevrolet', 'Metro', '0.65');
insert into car (id, make, model, price) values (320, 'Hyundai', 'Accent', '6.10');
insert into car (id, make, model, price) values (321, 'Buick', 'Regal', '9.29');
insert into car (id, make, model, price) values (322, 'Dodge', 'Dakota', '2.68');
insert into car (id, make, model, price) values (323, 'Honda', 'Element', '6.34');
insert into car (id, make, model, price) values (324, 'Acura', 'MDX', '9.18');
insert into car (id, make, model, price) values (325, 'Ford', 'Tempo', '6.49');
insert into car (id, make, model, price) values (326, 'Volvo', 'V90', '8.03');
insert into car (id, make, model, price) values (327, 'Mercedes-Benz', '300SE', '7.66');
insert into car (id, make, model, price) values (328, 'Hummer', 'H1', '8.90');
insert into car (id, make, model, price) values (329, 'GMC', 'Savana 2500', '4.90');
insert into car (id, make, model, price) values (330, 'Chevrolet', 'Suburban', '0.16');
insert into car (id, make, model, price) values (331, 'Ford', 'Bronco II', '2.65');
insert into car (id, make, model, price) values (332, 'Chrysler', 'Aspen', '1.57');
insert into car (id, make, model, price) values (333, 'Ford', 'F350', '0.44');
insert into car (id, make, model, price) values (334, 'Audi', '200', '9.78');
insert into car (id, make, model, price) values (335, 'Volvo', 'S80', '5.48');
insert into car (id, make, model, price) values (336, 'Mercury', 'Monterey', '1.73');
insert into car (id, make, model, price) values (337, 'Lexus', 'IS', '1.43');
insert into car (id, make, model, price) values (338, 'Acura', 'RL', '5.93');
insert into car (id, make, model, price) values (339, 'Pontiac', 'Grand Prix', '1.72');
insert into car (id, make, model, price) values (340, 'Aptera', 'Type-1h', '2.19');
insert into car (id, make, model, price) values (341, 'Acura', 'MDX', '8.11');
insert into car (id, make, model, price) values (342, 'Nissan', 'Armada', '6.72');
insert into car (id, make, model, price) values (343, 'Mitsubishi', 'Pajero', '6.48');
insert into car (id, make, model, price) values (344, 'Toyota', 'Tacoma', '9.02');
insert into car (id, make, model, price) values (345, 'Audi', '5000S', '6.20');
insert into car (id, make, model, price) values (346, 'Porsche', '928', '8.27');
insert into car (id, make, model, price) values (347, 'Hyundai', 'Accent', '6.17');
insert into car (id, make, model, price) values (348, 'Pontiac', 'Vibe', '3.56');
insert into car (id, make, model, price) values (349, 'Dodge', 'Stealth', '9.91');
insert into car (id, make, model, price) values (350, 'Toyota', 'Tacoma Xtra', '1.64');
insert into car (id, make, model, price) values (351, 'Ford', 'Escape', '5.34');
insert into car (id, make, model, price) values (352, 'Cadillac', 'Escalade EXT', '0.59');
insert into car (id, make, model, price) values (353, 'Honda', 'Ridgeline', '4.33');
insert into car (id, make, model, price) values (354, 'Mazda', 'MX-5', '3.00');
insert into car (id, make, model, price) values (355, 'Audi', 'A6', '2.83');
insert into car (id, make, model, price) values (356, 'Panoz', 'Esperante', '6.71');
insert into car (id, make, model, price) values (357, 'Ford', 'Transit Connect', '1.85');
insert into car (id, make, model, price) values (358, 'GMC', 'Rally Wagon G3500', '1.66');
insert into car (id, make, model, price) values (359, 'Chevrolet', 'Malibu', '1.33');
insert into car (id, make, model, price) values (360, 'Ford', 'F150', '7.88');
insert into car (id, make, model, price) values (361, 'Chevrolet', 'Express 2500', '7.62');
insert into car (id, make, model, price) values (362, 'Subaru', 'Impreza WRX', '3.14');
insert into car (id, make, model, price) values (363, 'Volkswagen', 'Passat', '1.92');
insert into car (id, make, model, price) values (364, 'Chevrolet', 'TrailBlazer', '0.15');
insert into car (id, make, model, price) values (365, 'Chevrolet', 'Caprice', '3.23');
insert into car (id, make, model, price) values (366, 'Rambler', 'Classic', '7.60');
insert into car (id, make, model, price) values (367, 'Eagle', 'Summit', '1.65');
insert into car (id, make, model, price) values (368, 'Volkswagen', 'Jetta', '0.71');
insert into car (id, make, model, price) values (369, 'Toyota', '4Runner', '7.09');
insert into car (id, make, model, price) values (370, 'Toyota', 'Prius Plug-in Hybrid', '0.60');
insert into car (id, make, model, price) values (371, 'Volkswagen', 'CC', '4.95');
insert into car (id, make, model, price) values (372, 'Chrysler', 'Imperial', '3.24');
insert into car (id, make, model, price) values (373, 'Volvo', 'S80', '3.26');
insert into car (id, make, model, price) values (374, 'Chevrolet', 'Corvette', '8.27');
insert into car (id, make, model, price) values (375, 'Acura', 'TL', '5.76');
insert into car (id, make, model, price) values (376, 'Ford', 'Tempo', '0.42');
insert into car (id, make, model, price) values (377, 'GMC', 'Yukon', '7.34');
insert into car (id, make, model, price) values (378, 'Suzuki', 'Grand Vitara', '4.15');
insert into car (id, make, model, price) values (379, 'BMW', '6 Series', '1.71');
insert into car (id, make, model, price) values (380, 'Nissan', '240SX', '8.26');
insert into car (id, make, model, price) values (381, 'Dodge', 'Ram Wagon B250', '9.06');
insert into car (id, make, model, price) values (382, 'Chrysler', 'Cirrus', '2.59');
insert into car (id, make, model, price) values (383, 'Toyota', 'Sienna', '7.18');
insert into car (id, make, model, price) values (384, 'Chevrolet', 'Silverado 1500', '6.31');
insert into car (id, make, model, price) values (385, 'Mercedes-Benz', 'CL-Class', '9.22');
insert into car (id, make, model, price) values (386, 'Honda', 'Accord', '2.60');
insert into car (id, make, model, price) values (387, 'Plymouth', 'Voyager', '3.02');
insert into car (id, make, model, price) values (388, 'Chevrolet', 'Monte Carlo', '6.69');
insert into car (id, make, model, price) values (389, 'BMW', '525', '9.48');
insert into car (id, make, model, price) values (390, 'Cadillac', 'Escalade', '8.62');
insert into car (id, make, model, price) values (391, 'Dodge', 'Neon', '8.03');
insert into car (id, make, model, price) values (392, 'Austin', 'Mini Cooper', '4.14');
insert into car (id, make, model, price) values (393, 'Nissan', 'Pathfinder', '6.70');
insert into car (id, make, model, price) values (394, 'Suzuki', 'SJ 410', '6.08');
insert into car (id, make, model, price) values (395, 'Jeep', 'Cherokee', '6.56');
insert into car (id, make, model, price) values (396, 'Ford', 'F250', '6.68');
insert into car (id, make, model, price) values (397, 'Acura', 'Legend', '1.10');
insert into car (id, make, model, price) values (398, 'Jeep', 'Grand Cherokee', '2.71');
insert into car (id, make, model, price) values (399, 'Audi', 'A8', '6.35');
insert into car (id, make, model, price) values (400, 'Hyundai', 'Sonata', '8.09');
insert into car (id, make, model, price) values (401, 'Dodge', 'Journey', '9.10');
insert into car (id, make, model, price) values (402, 'Mazda', 'RX-7', '1.78');
insert into car (id, make, model, price) values (403, 'Mercedes-Benz', 'Sprinter', '1.32');
insert into car (id, make, model, price) values (404, 'Ford', 'Escape', '5.12');
insert into car (id, make, model, price) values (405, 'Hummer', 'H2 SUT', '9.94');
insert into car (id, make, model, price) values (406, 'Volvo', 'S80', '2.85');
insert into car (id, make, model, price) values (407, 'Lamborghini', 'Gallardo', '5.47');
insert into car (id, make, model, price) values (408, 'Honda', 'Accord', '4.09');
insert into car (id, make, model, price) values (409, 'Lincoln', 'Town Car', '2.02');
insert into car (id, make, model, price) values (410, 'Mazda', 'B-Series Plus', '0.06');
insert into car (id, make, model, price) values (411, 'Lexus', 'SC', '10.00');
insert into car (id, make, model, price) values (412, 'Mitsubishi', 'Tredia', '3.66');
insert into car (id, make, model, price) values (413, 'Hyundai', 'Sonata', '1.57');
insert into car (id, make, model, price) values (414, 'Lexus', 'ES', '7.19');
insert into car (id, make, model, price) values (415, 'Ford', 'F-Series', '4.24');
insert into car (id, make, model, price) values (416, 'Geo', 'Prizm', '0.22');
insert into car (id, make, model, price) values (417, 'Lexus', 'ES', '0.34');
insert into car (id, make, model, price) values (418, 'Buick', 'Century', '3.27');
insert into car (id, make, model, price) values (419, 'Acura', 'TL', '8.94');
insert into car (id, make, model, price) values (420, 'Ford', 'Thunderbird', '8.49');
insert into car (id, make, model, price) values (421, 'Audi', 'A4', '6.16');
insert into car (id, make, model, price) values (422, 'Mercedes-Benz', 'SLR McLaren', '2.21');
insert into car (id, make, model, price) values (423, 'Volvo', 'XC60', '7.63');
insert into car (id, make, model, price) values (424, 'Acura', 'RDX', '9.45');
insert into car (id, make, model, price) values (425, 'Dodge', 'Avenger', '3.77');
insert into car (id, make, model, price) values (426, 'Chevrolet', 'Impala SS', '6.93');
insert into car (id, make, model, price) values (427, 'Land Rover', 'Range Rover', '3.75');
insert into car (id, make, model, price) values (428, 'Ford', 'Bronco II', '2.28');
insert into car (id, make, model, price) values (429, 'Lexus', 'ES', '7.96');
insert into car (id, make, model, price) values (430, 'GMC', 'Yukon', '1.09');
insert into car (id, make, model, price) values (431, 'Chevrolet', 'Tracker', '5.18');
insert into car (id, make, model, price) values (432, 'Hummer', 'H3T', '1.57');
insert into car (id, make, model, price) values (433, 'Honda', 'Civic', '6.42');
insert into car (id, make, model, price) values (434, 'Aptera', 'Type-1h', '9.01');
insert into car (id, make, model, price) values (435, 'Chevrolet', 'Camaro', '7.63');
insert into car (id, make, model, price) values (436, 'GMC', 'Sonoma', '6.90');
insert into car (id, make, model, price) values (437, 'Ford', 'Freestyle', '7.55');
insert into car (id, make, model, price) values (438, 'Dodge', 'Ram 2500', '9.15');
insert into car (id, make, model, price) values (439, 'Pontiac', 'Aztek', '7.22');
insert into car (id, make, model, price) values (440, 'Jaguar', 'XJ Series', '2.14');
insert into car (id, make, model, price) values (441, 'Ford', 'F-Series', '3.08');
insert into car (id, make, model, price) values (442, 'Chevrolet', 'Malibu', '1.45');
insert into car (id, make, model, price) values (443, 'GMC', 'Suburban 2500', '9.73');
insert into car (id, make, model, price) values (444, 'Pontiac', 'Grand Am', '3.58');
insert into car (id, make, model, price) values (445, 'Toyota', 'Corolla', '7.13');
insert into car (id, make, model, price) values (446, 'Acura', 'Vigor', '4.65');
insert into car (id, make, model, price) values (447, 'Volkswagen', 'Golf', '9.06');
insert into car (id, make, model, price) values (448, 'Dodge', 'Viper', '0.27');
insert into car (id, make, model, price) values (449, 'Saturn', 'VUE', '9.38');
insert into car (id, make, model, price) values (450, 'Ford', 'Windstar', '3.52');
insert into car (id, make, model, price) values (451, 'Lincoln', 'MKX', '4.31');
insert into car (id, make, model, price) values (452, 'Buick', 'Riviera', '0.90');
insert into car (id, make, model, price) values (453, 'GMC', 'Savana 3500', '7.20');
insert into car (id, make, model, price) values (454, 'Ford', 'F250', '2.95');
insert into car (id, make, model, price) values (455, 'Volkswagen', 'Passat', '5.32');
insert into car (id, make, model, price) values (456, 'Chevrolet', 'TrailBlazer', '7.71');
insert into car (id, make, model, price) values (457, 'Infiniti', 'G', '6.05');
insert into car (id, make, model, price) values (458, 'Dodge', 'Durango', '1.55');
insert into car (id, make, model, price) values (459, 'Plymouth', 'Breeze', '0.49');
insert into car (id, make, model, price) values (460, 'GMC', 'Rally Wagon 2500', '1.73');
insert into car (id, make, model, price) values (461, 'Lotus', 'Esprit Turbo', '9.14');
insert into car (id, make, model, price) values (462, 'Mitsubishi', 'GTO', '1.36');
insert into car (id, make, model, price) values (463, 'Lincoln', 'Town Car', '2.81');
insert into car (id, make, model, price) values (464, 'Dodge', 'Intrepid', '3.42');
insert into car (id, make, model, price) values (465, 'Chevrolet', 'Caprice', '9.90');
insert into car (id, make, model, price) values (466, 'Dodge', 'Avenger', '5.41');
insert into car (id, make, model, price) values (467, 'Subaru', 'Alcyone SVX', '6.47');
insert into car (id, make, model, price) values (468, 'Nissan', 'Murano', '9.61');
insert into car (id, make, model, price) values (469, 'Ford', 'F-Series', '0.61');
insert into car (id, make, model, price) values (470, 'Toyota', 'Land Cruiser', '1.93');
insert into car (id, make, model, price) values (471, 'Lincoln', 'Continental', '1.01');
insert into car (id, make, model, price) values (472, 'Audi', 'A8', '9.85');
insert into car (id, make, model, price) values (473, 'Toyota', 'Tacoma', '9.04');
insert into car (id, make, model, price) values (474, 'Isuzu', 'Axiom', '4.13');
insert into car (id, make, model, price) values (475, 'Ford', 'F-Series', '2.34');
insert into car (id, make, model, price) values (476, 'Mitsubishi', 'Pajero', '9.75');
insert into car (id, make, model, price) values (477, 'Chevrolet', 'Corvette', '5.41');
insert into car (id, make, model, price) values (478, 'Mazda', 'MX-5', '1.08');
insert into car (id, make, model, price) values (479, 'Saab', '9-3', '6.08');
insert into car (id, make, model, price) values (480, 'Subaru', 'B9 Tribeca', '5.26');
insert into car (id, make, model, price) values (481, 'Audi', 'A8', '4.91');
insert into car (id, make, model, price) values (482, 'Ford', 'Mustang', '2.29');
insert into car (id, make, model, price) values (483, 'Lotus', 'Exige', '5.90');
insert into car (id, make, model, price) values (484, 'Aston Martin', 'V8 Vantage', '4.34');
insert into car (id, make, model, price) values (485, 'Pontiac', 'Bonneville', '2.09');
insert into car (id, make, model, price) values (486, 'Mitsubishi', 'Eclipse', '2.22');
insert into car (id, make, model, price) values (487, 'Ford', 'Taurus', '6.45');
insert into car (id, make, model, price) values (488, 'Honda', 'Civic Si', '3.09');
insert into car (id, make, model, price) values (489, 'Mazda', 'Mazda3', '2.58');
insert into car (id, make, model, price) values (490, 'Mazda', 'Protege', '6.16');
insert into car (id, make, model, price) values (491, 'GMC', 'Sonoma', '1.56');
insert into car (id, make, model, price) values (492, 'Saab', '9-7X', '4.74');
insert into car (id, make, model, price) values (493, 'Mercedes-Benz', 'G-Class', '8.56');
insert into car (id, make, model, price) values (494, 'Infiniti', 'FX', '1.04');
insert into car (id, make, model, price) values (495, 'Isuzu', 'Ascender', '1.48');
insert into car (id, make, model, price) values (496, 'Mazda', 'B-Series', '7.81');
insert into car (id, make, model, price) values (497, 'BMW', 'X3', '6.28');
insert into car (id, make, model, price) values (498, 'Mercury', 'Milan', '9.37');
insert into car (id, make, model, price) values (499, 'Porsche', '911', '3.86');
insert into car (id, make, model, price) values (500, 'Toyota', 'Land Cruiser', '7.83');
insert into car (id, make, model, price) values (501, 'Mercedes-Benz', 'CL-Class', '8.36');
insert into car (id, make, model, price) values (502, 'Pontiac', 'Firebird', '0.03');
insert into car (id, make, model, price) values (503, 'Audi', 'S8', '6.64');
insert into car (id, make, model, price) values (504, 'Mercury', 'Grand Marquis', '1.00');
insert into car (id, make, model, price) values (505, 'GMC', 'Safari', '4.17');
insert into car (id, make, model, price) values (506, 'BMW', '3 Series', '4.69');
insert into car (id, make, model, price) values (507, 'Volkswagen', 'Eurovan', '8.25');
insert into car (id, make, model, price) values (508, 'Buick', 'Century', '2.66');
insert into car (id, make, model, price) values (509, 'Oldsmobile', 'Alero', '0.47');
insert into car (id, make, model, price) values (510, 'Chevrolet', 'Corvette', '7.84');
insert into car (id, make, model, price) values (511, 'Nissan', 'Quest', '5.69');
insert into car (id, make, model, price) values (512, 'Honda', 'Passport', '6.60');
insert into car (id, make, model, price) values (513, 'Honda', 'Insight', '2.77');
insert into car (id, make, model, price) values (514, 'Chevrolet', 'Silverado 2500', '7.44');
insert into car (id, make, model, price) values (515, 'Lotus', 'Elise', '1.21');
insert into car (id, make, model, price) values (516, 'Mercury', 'Sable', '1.33');
insert into car (id, make, model, price) values (517, 'Mercedes-Benz', 'E-Class', '5.28');
insert into car (id, make, model, price) values (518, 'Toyota', 'Avalon', '7.37');
insert into car (id, make, model, price) values (519, 'Nissan', 'Pathfinder', '0.69');
insert into car (id, make, model, price) values (520, 'Toyota', 'Tacoma', '9.90');
insert into car (id, make, model, price) values (521, 'Mitsubishi', 'Lancer', '7.11');
insert into car (id, make, model, price) values (522, 'Honda', 'Accord', '5.69');
insert into car (id, make, model, price) values (523, 'Maserati', 'GranSport', '3.45');
insert into car (id, make, model, price) values (524, 'BMW', 'Z4', '2.08');
insert into car (id, make, model, price) values (525, 'Cadillac', 'Escalade', '3.26');
insert into car (id, make, model, price) values (526, 'Lexus', 'GS', '4.00');
insert into car (id, make, model, price) values (527, 'BMW', 'M6', '5.60');
insert into car (id, make, model, price) values (528, 'Saab', '9-5', '5.27');
insert into car (id, make, model, price) values (529, 'Ford', 'Focus', '6.31');
insert into car (id, make, model, price) values (530, 'Audi', 'A6', '2.59');
insert into car (id, make, model, price) values (531, 'Mitsubishi', 'Pajero', '8.29');
insert into car (id, make, model, price) values (532, 'Chevrolet', 'Suburban 2500', '9.76');
insert into car (id, make, model, price) values (533, 'Dodge', 'Viper', '6.47');
insert into car (id, make, model, price) values (534, 'Mazda', 'Miata MX-5', '2.16');
insert into car (id, make, model, price) values (535, 'GMC', 'Savana 2500', '8.06');
insert into car (id, make, model, price) values (536, 'Acura', 'ZDX', '8.73');
insert into car (id, make, model, price) values (537, 'Mazda', 'Miata MX-5', '6.90');
insert into car (id, make, model, price) values (538, 'Suzuki', 'Daewoo Lacetti', '0.14');
insert into car (id, make, model, price) values (539, 'Mercedes-Benz', 'SL65 AMG', '8.01');
insert into car (id, make, model, price) values (540, 'Porsche', '968', '3.20');
insert into car (id, make, model, price) values (541, 'Isuzu', 'i-Series', '4.97');
insert into car (id, make, model, price) values (542, 'Dodge', 'Dakota Club', '6.76');
insert into car (id, make, model, price) values (543, 'Audi', 'riolet', '5.81');
insert into car (id, make, model, price) values (544, 'Mercedes-Benz', 'S-Class', '9.29');
insert into car (id, make, model, price) values (545, 'Aston Martin', 'DB9 Volante', '5.94');
insert into car (id, make, model, price) values (546, 'GMC', 'Suburban 2500', '6.73');
insert into car (id, make, model, price) values (547, 'Nissan', '280ZX', '8.11');
insert into car (id, make, model, price) values (548, 'Pontiac', 'Firefly', '0.55');
insert into car (id, make, model, price) values (549, 'Infiniti', 'G', '7.17');
insert into car (id, make, model, price) values (550, 'Honda', 'CR-V', '7.03');
insert into car (id, make, model, price) values (551, 'Mercury', 'Sable', '0.67');
insert into car (id, make, model, price) values (552, 'Mercedes-Benz', '600SEC', '0.49');
insert into car (id, make, model, price) values (553, 'Mitsubishi', 'Pajero', '0.25');
insert into car (id, make, model, price) values (554, 'Suzuki', 'SJ', '6.18');
insert into car (id, make, model, price) values (555, 'Volkswagen', 'Golf', '7.22');
insert into car (id, make, model, price) values (556, 'Lexus', 'LS', '3.16');
insert into car (id, make, model, price) values (557, 'GMC', 'Yukon', '2.11');
insert into car (id, make, model, price) values (558, 'Mercedes-Benz', 'E-Class', '6.08');
insert into car (id, make, model, price) values (559, 'Cadillac', 'Escalade', '0.22');
insert into car (id, make, model, price) values (560, 'Suzuki', 'Swift', '9.30');
insert into car (id, make, model, price) values (561, 'Nissan', 'Xterra', '9.70');
insert into car (id, make, model, price) values (562, 'Buick', 'Riviera', '1.07');
insert into car (id, make, model, price) values (563, 'Chevrolet', 'Camaro', '7.24');
insert into car (id, make, model, price) values (564, 'Chevrolet', 'S10 Blazer', '0.10');
insert into car (id, make, model, price) values (565, 'Hummer', 'H1', '3.43');
insert into car (id, make, model, price) values (566, 'Hyundai', 'Equus', '3.11');
insert into car (id, make, model, price) values (567, 'GMC', 'Envoy XL', '0.69');
insert into car (id, make, model, price) values (568, 'Dodge', 'Dakota Club', '5.10');
insert into car (id, make, model, price) values (569, 'Volkswagen', 'Touareg', '5.28');
insert into car (id, make, model, price) values (570, 'Pontiac', 'Grand Prix', '8.00');
insert into car (id, make, model, price) values (571, 'Land Rover', 'Range Rover', '1.08');
insert into car (id, make, model, price) values (572, 'Dodge', 'D150 Club', '0.20');
insert into car (id, make, model, price) values (573, 'Jaguar', 'XJ', '3.87');
insert into car (id, make, model, price) values (574, 'Dodge', 'Ram 3500', '10.00');
insert into car (id, make, model, price) values (575, 'BMW', '3 Series', '0.67');
insert into car (id, make, model, price) values (576, 'Mazda', 'B-Series', '4.61');
insert into car (id, make, model, price) values (577, 'Ford', 'F150', '2.37');
insert into car (id, make, model, price) values (578, 'Volvo', 'XC70', '9.71');
insert into car (id, make, model, price) values (579, 'BMW', 'X5', '0.12');
insert into car (id, make, model, price) values (580, 'Mercury', 'Cougar', '4.54');
insert into car (id, make, model, price) values (581, 'Cadillac', 'CTS-V', '5.23');
insert into car (id, make, model, price) values (582, 'BMW', '3 Series', '7.60');
insert into car (id, make, model, price) values (583, 'BMW', '3 Series', '3.31');
insert into car (id, make, model, price) values (584, 'Ford', 'Expedition EL', '9.35');
insert into car (id, make, model, price) values (585, 'Buick', 'Century', '0.98');
insert into car (id, make, model, price) values (586, 'Chevrolet', 'Colorado', '8.27');
insert into car (id, make, model, price) values (587, 'Chevrolet', 'Corvette', '2.50');
insert into car (id, make, model, price) values (588, 'Ferrari', 'F430', '6.34');
insert into car (id, make, model, price) values (589, 'Chevrolet', 'Cruze', '6.45');
insert into car (id, make, model, price) values (590, 'Mitsubishi', 'Lancer', '0.54');
insert into car (id, make, model, price) values (591, 'Mazda', 'Tribute', '5.58');
insert into car (id, make, model, price) values (592, 'Chevrolet', '3500', '5.10');
insert into car (id, make, model, price) values (593, 'Mercedes-Benz', 'GL-Class', '4.73');
insert into car (id, make, model, price) values (594, 'Buick', 'Hearse', '0.41');
insert into car (id, make, model, price) values (595, 'Subaru', 'Impreza', '8.81');
insert into car (id, make, model, price) values (596, 'Scion', 'xB', '4.04');
insert into car (id, make, model, price) values (597, 'Eagle', 'Talon', '6.78');
insert into car (id, make, model, price) values (598, 'Ford', 'Expedition EL', '1.74');
insert into car (id, make, model, price) values (599, 'GMC', 'Rally Wagon G3500', '4.40');
insert into car (id, make, model, price) values (600, 'Pontiac', 'Grand Prix', '0.34');
insert into car (id, make, model, price) values (601, 'Ford', 'Explorer Sport Trac', '5.94');
insert into car (id, make, model, price) values (602, 'Dodge', 'D350', '6.79');
insert into car (id, make, model, price) values (603, 'Nissan', 'Maxima', '4.77');
insert into car (id, make, model, price) values (604, 'Acura', 'RL', '2.15');
insert into car (id, make, model, price) values (605, 'Mercedes-Benz', '400E', '6.04');
insert into car (id, make, model, price) values (606, 'Ford', 'Taurus X', '3.27');
insert into car (id, make, model, price) values (607, 'Saab', '9-7X', '3.22');
insert into car (id, make, model, price) values (608, 'Audi', 'Q5', '7.49');
insert into car (id, make, model, price) values (609, 'Infiniti', 'FX', '2.72');
insert into car (id, make, model, price) values (610, 'Acura', 'NSX', '5.66');
insert into car (id, make, model, price) values (611, 'Mitsubishi', 'Pajero', '5.59');
insert into car (id, make, model, price) values (612, 'Chevrolet', 'Tahoe', '6.92');
insert into car (id, make, model, price) values (613, 'Infiniti', 'Q', '2.93');
insert into car (id, make, model, price) values (614, 'Toyota', 'Venza', '7.70');
insert into car (id, make, model, price) values (615, 'Dodge', 'Ram 3500', '8.36');
insert into car (id, make, model, price) values (616, 'Volvo', 'S40', '2.18');
insert into car (id, make, model, price) values (617, 'GMC', 'Yukon', '2.00');
insert into car (id, make, model, price) values (618, 'Mitsubishi', 'Chariot', '8.92');
insert into car (id, make, model, price) values (619, 'Nissan', 'Pathfinder', '9.44');
insert into car (id, make, model, price) values (620, 'Mercury', 'Villager', '5.43');
insert into car (id, make, model, price) values (621, 'Ford', 'Mustang', '7.95');
insert into car (id, make, model, price) values (622, 'Volkswagen', 'R32', '7.15');
insert into car (id, make, model, price) values (623, 'Mitsubishi', '3000GT', '4.63');
insert into car (id, make, model, price) values (624, 'GMC', 'Yukon XL 2500', '3.39');
insert into car (id, make, model, price) values (625, 'Lincoln', 'Navigator', '8.84');
insert into car (id, make, model, price) values (626, 'Lexus', 'LS', '2.59');
insert into car (id, make, model, price) values (627, 'Mazda', 'MPV', '0.67');
insert into car (id, make, model, price) values (628, 'Chevrolet', 'Corsica', '3.41');
insert into car (id, make, model, price) values (629, 'Jeep', 'Compass', '2.79');
insert into car (id, make, model, price) values (630, 'Mitsubishi', 'Diamante', '8.24');
insert into car (id, make, model, price) values (631, 'Kia', 'Rio', '5.23');
insert into car (id, make, model, price) values (632, 'Mazda', 'Mazda3', '1.13');
insert into car (id, make, model, price) values (633, 'Pontiac', 'Sunbird', '4.32');
insert into car (id, make, model, price) values (634, 'Acura', 'MDX', '6.41');
insert into car (id, make, model, price) values (635, 'Saab', '900', '6.25');
insert into car (id, make, model, price) values (636, 'Chevrolet', 'Corvette', '5.21');
insert into car (id, make, model, price) values (637, 'Ford', 'Festiva', '6.50');
insert into car (id, make, model, price) values (638, 'Mitsubishi', 'Eclipse', '6.51');
insert into car (id, make, model, price) values (639, 'Ford', 'Thunderbird', '9.00');
insert into car (id, make, model, price) values (640, 'Lincoln', 'Navigator', '8.94');
insert into car (id, make, model, price) values (641, 'Scion', 'tC', '5.40');
insert into car (id, make, model, price) values (642, 'Mazda', 'Mazdaspeed 3', '5.74');
insert into car (id, make, model, price) values (643, 'Hyundai', 'Sonata', '2.43');
insert into car (id, make, model, price) values (644, 'Ford', 'Ranger', '8.65');
insert into car (id, make, model, price) values (645, 'Toyota', '4Runner', '4.05');
insert into car (id, make, model, price) values (646, 'Honda', 'Civic', '7.88');
insert into car (id, make, model, price) values (647, 'Mercury', 'Grand Marquis', '2.60');
insert into car (id, make, model, price) values (648, 'Mercedes-Benz', 'SL-Class', '3.84');
insert into car (id, make, model, price) values (649, 'Volvo', 'C70', '7.23');
insert into car (id, make, model, price) values (650, 'Dodge', 'Caravan', '1.91');
insert into car (id, make, model, price) values (651, 'Dodge', 'Ram 2500', '2.61');
insert into car (id, make, model, price) values (652, 'Nissan', 'Maxima', '9.91');
insert into car (id, make, model, price) values (653, 'Mercedes-Benz', 'CLK-Class', '9.71');
insert into car (id, make, model, price) values (654, 'Volkswagen', 'Routan', '2.32');
insert into car (id, make, model, price) values (655, 'Audi', 'R8', '6.92');
insert into car (id, make, model, price) values (656, 'Toyota', 'Avalon', '6.64');
insert into car (id, make, model, price) values (657, 'Chevrolet', 'Monte Carlo', '9.18');
insert into car (id, make, model, price) values (658, 'Mitsubishi', 'Cordia', '0.20');
insert into car (id, make, model, price) values (659, 'Chevrolet', 'Silverado 1500', '8.70');
insert into car (id, make, model, price) values (660, 'Mercedes-Benz', 'SLK-Class', '8.40');
insert into car (id, make, model, price) values (661, 'Toyota', 'Land Cruiser', '8.96');
insert into car (id, make, model, price) values (662, 'Oldsmobile', 'Cutlass', '7.84');
insert into car (id, make, model, price) values (663, 'Lincoln', 'LS', '3.17');
insert into car (id, make, model, price) values (664, 'Pontiac', 'Sunbird', '0.77');
insert into car (id, make, model, price) values (665, 'Volkswagen', 'Passat', '6.80');
insert into car (id, make, model, price) values (666, 'Hyundai', 'Genesis', '3.17');
insert into car (id, make, model, price) values (667, 'Audi', '90', '3.09');
insert into car (id, make, model, price) values (668, 'Mazda', 'CX-9', '5.09');
insert into car (id, make, model, price) values (669, 'Suzuki', 'Cultus', '9.13');
insert into car (id, make, model, price) values (670, 'Acura', 'Legend', '9.61');
insert into car (id, make, model, price) values (671, 'Subaru', 'XT', '7.71');
insert into car (id, make, model, price) values (672, 'Ford', 'F-Series Super Duty', '2.84');
insert into car (id, make, model, price) values (673, 'Dodge', 'Stratus', '2.09');
insert into car (id, make, model, price) values (674, 'Lamborghini', 'Diablo', '7.00');
insert into car (id, make, model, price) values (675, 'Dodge', 'Daytona', '9.19');
insert into car (id, make, model, price) values (676, 'Toyota', 'Avalon', '2.85');
insert into car (id, make, model, price) values (677, 'MINI', 'Cooper Clubman', '2.36');
insert into car (id, make, model, price) values (678, 'Ford', 'Econoline E350', '3.60');
insert into car (id, make, model, price) values (679, 'Dodge', 'Ram Van 2500', '6.70');
insert into car (id, make, model, price) values (680, 'Toyota', 'Venza', '8.19');
insert into car (id, make, model, price) values (681, 'Subaru', 'Impreza', '2.39');
insert into car (id, make, model, price) values (682, 'Toyota', 'Xtra', '0.82');
insert into car (id, make, model, price) values (683, 'Subaru', 'Outback', '2.27');
insert into car (id, make, model, price) values (684, 'Chrysler', 'New Yorker', '7.13');
insert into car (id, make, model, price) values (685, 'Mazda', 'Mazda6', '9.15');
insert into car (id, make, model, price) values (686, 'Ford', 'Windstar', '6.38');
insert into car (id, make, model, price) values (687, 'Mazda', 'RX-7', '5.99');
insert into car (id, make, model, price) values (688, 'Ford', 'Expedition', '9.69');
insert into car (id, make, model, price) values (689, 'Ford', 'Fusion', '7.04');
insert into car (id, make, model, price) values (690, 'Mercedes-Benz', 'C-Class', '3.86');
insert into car (id, make, model, price) values (691, 'Austin', 'Mini Cooper S', '1.10');
insert into car (id, make, model, price) values (692, 'Nissan', 'Datsun/Nissan Z-car', '6.78');
insert into car (id, make, model, price) values (693, 'Subaru', 'Alcyone SVX', '5.69');
insert into car (id, make, model, price) values (694, 'Honda', 'S2000', '8.22');
insert into car (id, make, model, price) values (695, 'GMC', 'Suburban 1500', '0.64');
insert into car (id, make, model, price) values (696, 'Volkswagen', 'Phaeton', '0.16');
insert into car (id, make, model, price) values (697, 'Toyota', 'Celica', '2.09');
insert into car (id, make, model, price) values (698, 'Nissan', 'Pathfinder', '4.07');
insert into car (id, make, model, price) values (699, 'Mercedes-Benz', '600SEL', '1.23');
insert into car (id, make, model, price) values (700, 'Mercedes-Benz', 'C-Class', '6.86');
insert into car (id, make, model, price) values (701, 'Porsche', '911', '4.81');
insert into car (id, make, model, price) values (702, 'Pontiac', 'Monterey', '5.01');
insert into car (id, make, model, price) values (703, 'Chevrolet', 'Express 2500', '1.48');
insert into car (id, make, model, price) values (704, 'Saturn', 'S-Series', '8.51');
insert into car (id, make, model, price) values (705, 'Pontiac', 'Sunbird', '6.69');
insert into car (id, make, model, price) values (706, 'Aston Martin', 'DB9', '7.38');
insert into car (id, make, model, price) values (707, 'Volkswagen', 'Golf', '4.99');
insert into car (id, make, model, price) values (708, 'Volkswagen', 'Jetta', '5.01');
insert into car (id, make, model, price) values (709, 'Chevrolet', 'G-Series 3500', '1.64');
insert into car (id, make, model, price) values (710, 'Honda', 'Element', '8.34');
insert into car (id, make, model, price) values (711, 'Ford', 'Five Hundred', '7.78');
insert into car (id, make, model, price) values (712, 'Jeep', 'Grand Cherokee', '9.97');
insert into car (id, make, model, price) values (713, 'Honda', 'Odyssey', '6.61');
insert into car (id, make, model, price) values (714, 'Dodge', 'Durango', '5.45');
insert into car (id, make, model, price) values (715, 'Kia', 'Sportage', '4.69');
insert into car (id, make, model, price) values (716, 'Volvo', 'S80', '7.65');
insert into car (id, make, model, price) values (717, 'Lincoln', 'Navigator', '2.16');
insert into car (id, make, model, price) values (718, 'Mazda', 'RX-7', '3.51');
insert into car (id, make, model, price) values (719, 'Chevrolet', 'Prizm', '3.42');
insert into car (id, make, model, price) values (720, 'Aston Martin', 'V12 Vantage', '3.48');
insert into car (id, make, model, price) values (721, 'Volkswagen', 'Passat', '3.10');
insert into car (id, make, model, price) values (722, 'Dodge', 'Sprinter', '7.55');
insert into car (id, make, model, price) values (723, 'Lexus', 'GX', '8.91');
insert into car (id, make, model, price) values (724, 'Buick', 'Enclave', '3.72');
insert into car (id, make, model, price) values (725, 'Pontiac', 'GTO', '1.10');
insert into car (id, make, model, price) values (726, 'Buick', 'Lucerne', '6.61');
insert into car (id, make, model, price) values (727, 'Mazda', 'MPV', '1.65');
insert into car (id, make, model, price) values (728, 'Oldsmobile', 'Ciera', '0.53');
insert into car (id, make, model, price) values (729, 'Ford', 'GT500', '8.01');
insert into car (id, make, model, price) values (730, 'Chrysler', 'Sebring', '1.21');
insert into car (id, make, model, price) values (731, 'Volkswagen', 'Corrado', '3.66');
insert into car (id, make, model, price) values (732, 'Ford', 'F-Series', '2.07');
insert into car (id, make, model, price) values (733, 'Geo', 'Prizm', '6.74');
insert into car (id, make, model, price) values (734, 'Mercedes-Benz', 'S-Class', '5.11');
insert into car (id, make, model, price) values (735, 'Mitsubishi', 'Expo', '1.54');
insert into car (id, make, model, price) values (736, 'Hyundai', 'Accent', '2.20');
insert into car (id, make, model, price) values (737, 'Buick', 'LeSabre', '6.49');
insert into car (id, make, model, price) values (738, 'Cadillac', 'Eldorado', '3.72');
insert into car (id, make, model, price) values (739, 'Mazda', 'Tribute', '9.33');
insert into car (id, make, model, price) values (740, 'Dodge', 'Charger', '3.63');
insert into car (id, make, model, price) values (741, 'Ford', 'E-Series', '0.67');
insert into car (id, make, model, price) values (742, 'Toyota', 'Tundra', '8.86');
insert into car (id, make, model, price) values (743, 'Mitsubishi', 'L300', '1.04');
insert into car (id, make, model, price) values (744, 'Ford', 'Taurus', '0.99');
insert into car (id, make, model, price) values (745, 'Pontiac', 'Grand Prix', '9.09');
insert into car (id, make, model, price) values (746, 'Lincoln', 'Mark LT', '7.29');
insert into car (id, make, model, price) values (747, 'Ford', 'Fiesta', '0.93');
insert into car (id, make, model, price) values (748, 'Audi', 'A3', '3.79');
insert into car (id, make, model, price) values (749, 'Audi', 'A6', '9.49');
insert into car (id, make, model, price) values (750, 'Maserati', 'Karif', '0.83');
insert into car (id, make, model, price) values (751, 'Subaru', 'SVX', '8.43');
insert into car (id, make, model, price) values (752, 'Kia', 'Sephia', '1.60');
insert into car (id, make, model, price) values (753, 'Maserati', '430', '1.18');
insert into car (id, make, model, price) values (754, 'GMC', 'Sierra', '4.38');
insert into car (id, make, model, price) values (755, 'Honda', 'Element', '5.01');
insert into car (id, make, model, price) values (756, 'GMC', 'Savana 2500', '7.23');
insert into car (id, make, model, price) values (757, 'Mercedes-Benz', 'SLK-Class', '8.13');
insert into car (id, make, model, price) values (758, 'Cadillac', 'STS-V', '7.52');
insert into car (id, make, model, price) values (759, 'Nissan', 'Quest', '2.75');
insert into car (id, make, model, price) values (760, 'Mitsubishi', 'Diamante', '5.61');
insert into car (id, make, model, price) values (761, 'Aptera', 'Typ-1', '6.49');
insert into car (id, make, model, price) values (762, 'Saturn', 'VUE', '2.78');
insert into car (id, make, model, price) values (763, 'Isuzu', 'i-Series', '9.66');
insert into car (id, make, model, price) values (764, 'Bentley', 'Continental', '6.59');
insert into car (id, make, model, price) values (765, 'Mercedes-Benz', 'W201', '0.66');
insert into car (id, make, model, price) values (766, 'Hyundai', 'Excel', '8.70');
insert into car (id, make, model, price) values (767, 'Chevrolet', 'Silverado 1500', '8.87');
insert into car (id, make, model, price) values (768, 'Mitsubishi', 'Mirage', '7.68');
insert into car (id, make, model, price) values (769, 'Chevrolet', '2500', '6.68');
insert into car (id, make, model, price) values (770, 'Mitsubishi', 'Montero Sport', '8.81');
insert into car (id, make, model, price) values (771, 'Ford', 'Escape', '6.32');
insert into car (id, make, model, price) values (772, 'Maybach', '62', '3.53');
insert into car (id, make, model, price) values (773, 'Pontiac', 'GTO', '5.86');
insert into car (id, make, model, price) values (774, 'Subaru', 'Legacy', '3.71');
insert into car (id, make, model, price) values (775, 'Chevrolet', 'Astro', '5.77');
insert into car (id, make, model, price) values (776, 'Ford', 'Thunderbird', '7.24');
insert into car (id, make, model, price) values (777, 'Aston Martin', 'V8 Vantage', '4.72');
insert into car (id, make, model, price) values (778, 'Saab', '9-7X', '7.05');
insert into car (id, make, model, price) values (779, 'Chevrolet', 'Express 3500', '4.84');
insert into car (id, make, model, price) values (780, 'Mitsubishi', 'Galant', '1.59');
insert into car (id, make, model, price) values (781, 'Dodge', 'Ram 2500 Club', '5.31');
insert into car (id, make, model, price) values (782, 'GMC', 'Sierra Hybrid', '8.79');
insert into car (id, make, model, price) values (783, 'Volkswagen', 'Jetta', '5.31');
insert into car (id, make, model, price) values (784, 'Buick', 'Century', '4.96');
insert into car (id, make, model, price) values (785, 'Mitsubishi', 'Galant', '9.50');
insert into car (id, make, model, price) values (786, 'BMW', 'M3', '4.83');
insert into car (id, make, model, price) values (787, 'Lotus', 'Elise', '7.61');
insert into car (id, make, model, price) values (788, 'Plymouth', 'Voyager', '6.59');
insert into car (id, make, model, price) values (789, 'Chevrolet', 'Prizm', '8.27');
insert into car (id, make, model, price) values (790, 'Ford', 'Econoline E150', '5.13');
insert into car (id, make, model, price) values (791, 'Toyota', 'TundraMax', '2.34');
insert into car (id, make, model, price) values (792, 'Buick', 'Electra', '1.23');
insert into car (id, make, model, price) values (793, 'Suzuki', 'Swift', '9.52');
insert into car (id, make, model, price) values (794, 'Honda', 'Accord', '9.89');
insert into car (id, make, model, price) values (795, 'Acura', 'MDX', '0.48');
insert into car (id, make, model, price) values (796, 'Mercedes-Benz', '500SEL', '9.97');
insert into car (id, make, model, price) values (797, 'Toyota', 'Sienna', '9.72');
insert into car (id, make, model, price) values (798, 'Volvo', 'S40', '8.56');
insert into car (id, make, model, price) values (799, 'Cadillac', 'Eldorado', '9.68');
insert into car (id, make, model, price) values (800, 'Mazda', 'Mazda3', '8.29');
insert into car (id, make, model, price) values (801, 'Maserati', 'Quattroporte', '6.11');
insert into car (id, make, model, price) values (802, 'Ford', 'Expedition EL', '4.90');
insert into car (id, make, model, price) values (803, 'Dodge', 'Intrepid', '5.82');
insert into car (id, make, model, price) values (804, 'Aston Martin', 'V8 Vantage', '4.10');
insert into car (id, make, model, price) values (805, 'Dodge', 'Stratus', '8.73');
insert into car (id, make, model, price) values (806, 'Lotus', 'Esprit', '4.99');
insert into car (id, make, model, price) values (807, 'Mazda', 'Miata MX-5', '4.96');
insert into car (id, make, model, price) values (808, 'Ford', 'Mustang', '0.53');
insert into car (id, make, model, price) values (809, 'Chevrolet', 'Astro', '3.50');
insert into car (id, make, model, price) values (810, 'Hummer', 'H1', '9.51');
insert into car (id, make, model, price) values (811, 'Hyundai', 'Equus', '4.70');
insert into car (id, make, model, price) values (812, 'Subaru', 'Legacy', '7.66');
insert into car (id, make, model, price) values (813, 'Honda', 'Element', '1.17');
insert into car (id, make, model, price) values (814, 'BMW', '7 Series', '1.53');
insert into car (id, make, model, price) values (815, 'Honda', 'Odyssey', '9.68');
insert into car (id, make, model, price) values (816, 'Lexus', 'LX', '6.74');
insert into car (id, make, model, price) values (817, 'GMC', 'Sierra 2500', '6.31');
insert into car (id, make, model, price) values (818, 'Audi', 'S4', '2.26');
insert into car (id, make, model, price) values (819, 'Pontiac', '6000', '6.71');
insert into car (id, make, model, price) values (820, 'Suzuki', 'Swift', '2.38');
insert into car (id, make, model, price) values (821, 'GMC', 'Sierra 1500', '1.96');
insert into car (id, make, model, price) values (822, 'Ford', 'E-Series', '4.72');
insert into car (id, make, model, price) values (823, 'Infiniti', 'FX', '6.49');
insert into car (id, make, model, price) values (824, 'Hyundai', 'XG350', '1.36');
insert into car (id, make, model, price) values (825, 'Nissan', 'Maxima', '1.90');
insert into car (id, make, model, price) values (826, 'Toyota', 'T100', '0.31');
insert into car (id, make, model, price) values (827, 'Pontiac', 'Parisienne', '7.78');
insert into car (id, make, model, price) values (828, 'Mazda', 'Millenia', '7.03');
insert into car (id, make, model, price) values (829, 'Volkswagen', 'New Beetle', '8.26');
insert into car (id, make, model, price) values (830, 'Volvo', 'XC90', '5.76');
insert into car (id, make, model, price) values (831, 'Ford', 'Econoline E150', '4.02');
insert into car (id, make, model, price) values (832, 'Pontiac', 'Aztek', '4.45');
insert into car (id, make, model, price) values (833, 'Mitsubishi', 'Lancer', '3.20');
insert into car (id, make, model, price) values (834, 'Toyota', 'Land Cruiser', '3.53');
insert into car (id, make, model, price) values (835, 'Subaru', 'Outback', '5.37');
insert into car (id, make, model, price) values (836, 'Mitsubishi', 'Mirage', '2.03');
insert into car (id, make, model, price) values (837, 'Volvo', 'S70', '7.64');
insert into car (id, make, model, price) values (838, 'Audi', '5000S', '4.52');
insert into car (id, make, model, price) values (839, 'Chevrolet', 'Camaro', '4.74');
insert into car (id, make, model, price) values (840, 'Chevrolet', 'Camaro', '6.15');
insert into car (id, make, model, price) values (841, 'Chrysler', '300M', '3.69');
insert into car (id, make, model, price) values (842, 'Cadillac', 'CTS', '1.77');
insert into car (id, make, model, price) values (843, 'Aston Martin', 'DB9', '6.71');
insert into car (id, make, model, price) values (844, 'Ford', 'Expedition', '6.51');
insert into car (id, make, model, price) values (845, 'Audi', 'A8', '6.11');
insert into car (id, make, model, price) values (846, 'Subaru', 'Brat', '2.50');
insert into car (id, make, model, price) values (847, 'Nissan', 'Rogue', '4.27');
insert into car (id, make, model, price) values (848, 'Buick', 'Estate', '4.32');
insert into car (id, make, model, price) values (849, 'Toyota', 'Prius', '4.30');
insert into car (id, make, model, price) values (850, 'Buick', 'Skyhawk', '0.11');
insert into car (id, make, model, price) values (851, 'Hyundai', 'Accent', '6.33');
insert into car (id, make, model, price) values (852, 'Holden', 'VS Commodore', '0.62');
insert into car (id, make, model, price) values (853, 'Audi', 'S6', '0.71');
insert into car (id, make, model, price) values (854, 'Chevrolet', 'Express 1500', '2.40');
insert into car (id, make, model, price) values (855, 'GMC', 'Rally Wagon 1500', '8.70');
insert into car (id, make, model, price) values (856, 'Saturn', 'L-Series', '7.84');
insert into car (id, make, model, price) values (857, 'Chevrolet', 'Avalanche 1500', '1.80');
insert into car (id, make, model, price) values (858, 'Ford', 'F250', '8.13');
insert into car (id, make, model, price) values (859, 'BMW', '5 Series', '3.20');
insert into car (id, make, model, price) values (860, 'Ferrari', '612 Scaglietti', '0.55');
insert into car (id, make, model, price) values (861, 'Mercedes-Benz', 'SLK-Class', '4.32');
insert into car (id, make, model, price) values (862, 'Audi', 'A6', '2.65');
insert into car (id, make, model, price) values (863, 'Honda', 'Accord', '1.48');
insert into car (id, make, model, price) values (864, 'BMW', '8 Series', '2.20');
insert into car (id, make, model, price) values (865, 'GMC', 'Sierra 2500', '0.70');
insert into car (id, make, model, price) values (866, 'Pontiac', 'GTO', '5.70');
insert into car (id, make, model, price) values (867, 'GMC', 'Sonoma', '1.71');
insert into car (id, make, model, price) values (868, 'Mercury', 'Cougar', '5.98');
insert into car (id, make, model, price) values (869, 'Dodge', 'Ram 2500', '5.91');
insert into car (id, make, model, price) values (870, 'Mitsubishi', 'Diamante', '5.93');
insert into car (id, make, model, price) values (871, 'Mitsubishi', 'Outlander', '2.81');
insert into car (id, make, model, price) values (872, 'Kia', 'Optima', '1.88');
insert into car (id, make, model, price) values (873, 'Porsche', 'Panamera', '7.66');
insert into car (id, make, model, price) values (874, 'Toyota', 'MR2', '0.26');
insert into car (id, make, model, price) values (875, 'Ram', '3500', '5.33');
insert into car (id, make, model, price) values (876, 'Jeep', 'Cherokee', '9.65');
insert into car (id, make, model, price) values (877, 'Volkswagen', 'Jetta', '1.20');
insert into car (id, make, model, price) values (878, 'Mercedes-Benz', 'E-Class', '2.12');
insert into car (id, make, model, price) values (879, 'Lincoln', 'Town Car', '5.22');
insert into car (id, make, model, price) values (880, 'Ford', 'Taurus', '2.41');
insert into car (id, make, model, price) values (881, 'Eagle', 'Talon', '9.47');
insert into car (id, make, model, price) values (882, 'Ford', 'Ranger', '6.55');
insert into car (id, make, model, price) values (883, 'Chevrolet', 'Malibu', '5.29');
insert into car (id, make, model, price) values (884, 'Chevrolet', 'S10 Blazer', '5.44');
insert into car (id, make, model, price) values (885, 'Chevrolet', 'Express 2500', '7.34');
insert into car (id, make, model, price) values (886, 'Mazda', 'B-Series', '5.75');
insert into car (id, make, model, price) values (887, 'Honda', 'Prelude', '9.94');
insert into car (id, make, model, price) values (888, 'Porsche', '911', '8.93');
insert into car (id, make, model, price) values (889, 'Mazda', 'MPV', '3.69');
insert into car (id, make, model, price) values (890, 'Dodge', 'Stratus', '5.32');
insert into car (id, make, model, price) values (891, 'Land Rover', 'Defender 90', '7.51');
insert into car (id, make, model, price) values (892, 'Jeep', 'Cherokee', '8.46');
insert into car (id, make, model, price) values (893, 'Buick', 'Skylark', '7.16');
insert into car (id, make, model, price) values (894, 'Chevrolet', 'Express 2500', '9.01');
insert into car (id, make, model, price) values (895, 'BMW', 'X5', '8.96');
insert into car (id, make, model, price) values (896, 'Infiniti', 'G', '7.09');
insert into car (id, make, model, price) values (897, 'Honda', 'del Sol', '5.10');
insert into car (id, make, model, price) values (898, 'Lexus', 'SC', '2.92');
insert into car (id, make, model, price) values (899, 'Isuzu', 'Rodeo Sport', '9.58');
insert into car (id, make, model, price) values (900, 'Subaru', 'Impreza', '3.84');
insert into car (id, make, model, price) values (901, 'Volkswagen', 'Jetta', '7.80');
insert into car (id, make, model, price) values (902, 'Mercury', 'Grand Marquis', '3.20');
insert into car (id, make, model, price) values (903, 'Toyota', 'Tacoma', '7.16');
insert into car (id, make, model, price) values (904, 'Audi', 'TT', '1.79');
insert into car (id, make, model, price) values (905, 'Chevrolet', '1500', '2.23');
insert into car (id, make, model, price) values (906, 'Buick', 'Century', '7.81');
insert into car (id, make, model, price) values (907, 'Hyundai', 'Veracruz', '5.93');
insert into car (id, make, model, price) values (908, 'MINI', 'Cooper Clubman', '2.57');
insert into car (id, make, model, price) values (909, 'Buick', 'Park Avenue', '4.78');
insert into car (id, make, model, price) values (910, 'Mercedes-Benz', 'S-Class', '3.05');
insert into car (id, make, model, price) values (911, 'Mazda', 'MX-5', '3.56');
insert into car (id, make, model, price) values (912, 'Lotus', 'Elise', '4.66');
insert into car (id, make, model, price) values (913, 'Lexus', 'ES', '3.58');
insert into car (id, make, model, price) values (914, 'GMC', 'Suburban 2500', '9.19');
insert into car (id, make, model, price) values (915, 'Saab', '9000', '6.99');
insert into car (id, make, model, price) values (916, 'Ford', 'Escape', '3.73');
insert into car (id, make, model, price) values (917, 'Mitsubishi', 'Tredia', '4.72');
insert into car (id, make, model, price) values (918, 'Ford', 'Expedition EL', '0.00');
insert into car (id, make, model, price) values (919, 'Chrysler', 'Town & Country', '5.70');
insert into car (id, make, model, price) values (920, 'BMW', '6 Series', '9.22');
insert into car (id, make, model, price) values (921, 'Toyota', 'Camry', '4.82');
insert into car (id, make, model, price) values (922, 'Cadillac', 'STS', '2.12');
insert into car (id, make, model, price) values (923, 'GMC', 'Sierra 3500', '0.49');
insert into car (id, make, model, price) values (924, 'Cadillac', 'DeVille', '7.34');
insert into car (id, make, model, price) values (925, 'Isuzu', 'Ascender', '8.18');
insert into car (id, make, model, price) values (926, 'Suzuki', 'Grand Vitara', '8.21');
insert into car (id, make, model, price) values (927, 'Volkswagen', 'Vanagon', '9.23');
insert into car (id, make, model, price) values (928, 'Maserati', 'Karif', '7.69');
insert into car (id, make, model, price) values (929, 'Cadillac', 'Escalade', '5.84');
insert into car (id, make, model, price) values (930, 'Buick', 'LaCrosse', '7.86');
insert into car (id, make, model, price) values (931, 'Suzuki', 'Vitara', '6.48');
insert into car (id, make, model, price) values (932, 'Chevrolet', 'Silverado 3500', '5.21');
insert into car (id, make, model, price) values (933, 'Chevrolet', 'Venture', '4.98');
insert into car (id, make, model, price) values (934, 'Subaru', 'Outback', '6.70');
insert into car (id, make, model, price) values (935, 'Chevrolet', 'Silverado', '0.69');
insert into car (id, make, model, price) values (936, 'Mitsubishi', 'Mirage', '4.27');
insert into car (id, make, model, price) values (937, 'Chevrolet', 'Cobalt', '8.87');
insert into car (id, make, model, price) values (938, 'Mazda', 'Protege', '9.91');
insert into car (id, make, model, price) values (939, 'GMC', 'Savana 2500', '8.71');
insert into car (id, make, model, price) values (940, 'BMW', '3 Series', '3.30');
insert into car (id, make, model, price) values (941, 'Toyota', 'Venza', '3.74');
insert into car (id, make, model, price) values (942, 'Jaguar', 'XK', '1.02');
insert into car (id, make, model, price) values (943, 'Volvo', 'V50', '5.03');
insert into car (id, make, model, price) values (944, 'Porsche', '911', '8.23');
insert into car (id, make, model, price) values (945, 'Chrysler', 'Town & Country', '7.74');
insert into car (id, make, model, price) values (946, 'Ford', 'Tempo', '4.05');
insert into car (id, make, model, price) values (947, 'Aston Martin', 'Vantage', '3.32');
insert into car (id, make, model, price) values (948, 'Chevrolet', 'Monte Carlo', '6.43');
insert into car (id, make, model, price) values (949, 'Audi', 'A3', '5.25');
insert into car (id, make, model, price) values (950, 'Isuzu', 'Impulse', '9.74');
insert into car (id, make, model, price) values (951, 'Mercury', 'Grand Marquis', '7.47');
insert into car (id, make, model, price) values (952, 'Ford', 'Escort', '1.84');
insert into car (id, make, model, price) values (953, 'Pontiac', 'Trans Sport', '6.51');
insert into car (id, make, model, price) values (954, 'Nissan', 'Titan', '8.38');
insert into car (id, make, model, price) values (955, 'BMW', 'X6', '0.91');
insert into car (id, make, model, price) values (956, 'Mazda', 'Protege', '4.93');
insert into car (id, make, model, price) values (957, 'Kia', 'Sportage', '5.48');
insert into car (id, make, model, price) values (958, 'Oldsmobile', 'Alero', '2.98');
insert into car (id, make, model, price) values (959, 'Cadillac', 'CTS', '8.90');
insert into car (id, make, model, price) values (960, 'Dodge', 'Ram Van 2500', '6.81');
insert into car (id, make, model, price) values (961, 'Toyota', 'Avalon', '1.78');
insert into car (id, make, model, price) values (962, 'Toyota', 'Prius', '5.72');
insert into car (id, make, model, price) values (963, 'Jeep', 'Liberty', '9.17');
insert into car (id, make, model, price) values (964, 'Toyota', 'Avalon', '7.87');
insert into car (id, make, model, price) values (965, 'Mercury', 'Grand Marquis', '2.26');
insert into car (id, make, model, price) values (966, 'Chevrolet', 'Silverado 3500', '7.45');
insert into car (id, make, model, price) values (967, 'Ford', 'Excursion', '2.52');
insert into car (id, make, model, price) values (968, 'Dodge', 'Ram Van 3500', '6.18');
insert into car (id, make, model, price) values (969, 'Chrysler', 'Concorde', '9.58');
insert into car (id, make, model, price) values (970, 'Volvo', 'XC90', '4.66');
insert into car (id, make, model, price) values (971, 'Mazda', '626', '3.99');
insert into car (id, make, model, price) values (972, 'Pontiac', 'Grand Prix', '7.62');
insert into car (id, make, model, price) values (973, 'Nissan', '240SX', '4.36');
insert into car (id, make, model, price) values (974, 'Honda', 'Odyssey', '5.35');
insert into car (id, make, model, price) values (975, 'Chevrolet', 'Silverado 2500', '2.66');
insert into car (id, make, model, price) values (976, 'Volkswagen', 'Routan', '7.19');
insert into car (id, make, model, price) values (977, 'Pontiac', '6000', '8.73');
insert into car (id, make, model, price) values (978, 'Kia', 'Rio', '9.63');
insert into car (id, make, model, price) values (979, 'Ford', 'Mustang', '8.28');
insert into car (id, make, model, price) values (980, 'Ford', 'Escort', '8.61');
insert into car (id, make, model, price) values (981, 'Mitsubishi', 'Precis', '7.15');
insert into car (id, make, model, price) values (982, 'Hyundai', 'Sonata', '7.37');
insert into car (id, make, model, price) values (983, 'Chrysler', 'Concorde', '0.40');
insert into car (id, make, model, price) values (984, 'Pontiac', 'Gemini', '0.02');
insert into car (id, make, model, price) values (985, 'Nissan', 'Xterra', '2.38');
insert into car (id, make, model, price) values (986, 'Lamborghini', 'Diablo', '8.67');
insert into car (id, make, model, price) values (987, 'Saturn', 'S-Series', '8.20');
insert into car (id, make, model, price) values (988, 'Suzuki', 'Swift', '7.43');
insert into car (id, make, model, price) values (989, 'Chevrolet', 'Camaro', '8.98');
insert into car (id, make, model, price) values (990, 'Chevrolet', 'Corvette', '4.37');
insert into car (id, make, model, price) values (991, 'Chevrolet', 'G-Series G10', '2.34');
insert into car (id, make, model, price) values (992, 'Acura', 'TSX', '0.15');
insert into car (id, make, model, price) values (993, 'Mercedes-Benz', 'C-Class', '8.44');
insert into car (id, make, model, price) values (994, 'Ford', 'F250', '1.95');
insert into car (id, make, model, price) values (995, 'Lincoln', 'Blackwood', '9.89');
insert into car (id, make, model, price) values (996, 'BMW', 'X5', '8.95');
insert into car (id, make, model, price) values (997, 'Lexus', 'LX', '9.18');
insert into car (id, make, model, price) values (998, 'Nissan', '300ZX', '3.95');
insert into car (id, make, model, price) values (999, 'Dodge', 'Ram 1500 Club', '6.44');
insert into car (id, make, model, price) values (1000, 'Hyundai', 'Sonata', '2.81');
